api_key: null
base_url: http://localhost:11434
config_version: '1.0'
default_chat_mode: false
default_max_workers: null
default_model: codellama:7b-instruct
default_models: []
default_provider: ollama
default_save: true
default_stream: false
default_system_prompt: system_prompts/blockchain_tech_writer.md
default_timeout: 1200
default_user_prompt: user_prompts/wallet_setup_guide.md
openai_base_url: https://api.openai.com
use_menu: true
